Categories:
  - Writing
License: GPL-3.0-or-later
Web Site: https://github.com/adrianmalacoda/text-editor-8000
Source Code: https://github.com/adrianmalacoda/text-editor-8000
Issue Tracker: https://github.com/adrianmalacoda/text-editor-8000/issues

Auto Name: Text Editor 8000
Summary: Simple text editor
Description: Simple, yet powerful editor for text files.

Repo Type: git
Repo: https://github.com/adrianmalacoda/text-editor-8000

builds:
  - versionName: 1.20
    versionCode: 48
    commit: metadata-test
    subdir: app
    gradle: yes

Auto Update Mode: None
Update Check Mode: RepoManifest
Current Version: 1.20
Current Version Code: 48
