Categories:
  - Writing
License: GPL-3.0-or-later
WebSite: https://github.com/adrianmalacoda/text-editor-8000
SourceCode: https://github.com/adrianmalacoda/text-editor-8000
IssueTracker: https://github.com/adrianmalacoda/text-editor-8000/issues

AutoName: Text Editor 8000
Summary: Simple text editor
Description: Simple, yet powerful editor for text files.

RepoType: git
Repo: .

builds:
  - versionName: "1.20"
    versionCode: 48
    commit: HEAD
    subdir: app
    gradle: yes

AutoUpdateMode: None
UpdateCheckMode: RepoManifest
CurrentVersion: 1.20
CurrentVersion Code: 48
